Lesson 5
aivakhnenko/test_guru pull request #5
Opened 2018-09-16 14:30 UTC by aivakhnenko

2018-09-16 17:17 UTC, iBublik requested changes

2018-09-16 17:17 UTC, iBublik commented on app/models/category.rb
> +  has_many :tests
При создании `has_*` ассоциации стоит указывать что делать с дочерними записями при удалении родителя (опция dependent). Сейчас ты не сможешь удалить категорию, у которой есть тесты

2018-09-16 17:17 UTC, iBublik commented on app/models/test.rb
> +  belongs_to :user
Не очень понятное название ассоциации. Когда в коде увидишь `test.user`, сходу невозможно понять что же это за пользователь. Стоит дать более говорящее имя

2018-09-16 17:17 UTC, iBublik commented on app/models/user.rb
> +    Test.joins(:users).where(tests: { level: level }, users: { id: id })
Тут все еще проще - `tests.where(level: level)`. Все промежуточные запросы за тебя построит рельса, она знает как это сделать из описания связей

2018-09-16 17:17 UTC, iBublik commented on db/migrate/20180916133640_create_tests_users_join_table.rb
> +    create_join_table :users, :tests do |t|
Не вижу преимуществ перед обычной таблицей. А вот недостаток есть - отстутствие id не позволит связать эту таблицу с другой сущностью. Например, если мы захотим хранить ответы, выбранные пользователем при прохождении теста - логичнее всего было бы хранить id попытки прохождения и id ответа. Но у таблицы с попытками прохождения id нет, так что придется как-то по-другому это делать

2018-09-16 17:17 UTC, iBublik commented on db/seeds.rb
> +  { category_id: categories[0].id, level: 0, user_id: users[2].id, title: 'HTML' },
Теперь благодаря ассоциациям можно писать `user: user[2]`. id за тебя выставит рельса

2018-09-16 17:17 UTC, iBublik commented on db/migrate/20180916133640_create_tests_users_join_table.rb
> +      t.index [:user_id, :test_id], unique: true
Вообще у нас не запрещено дважды проходить один и тот же тест.
И в целом я бы оставил 2 отдельных индекса. Иначе, если мы захотим получить всех пользователей, которые проходили какой-то конкретный тест, такой запрос не сможет использовать индекс, будет полный скан таблицы. А с раздельными индексами все будет ок.

2018-09-18 19:13 UTC, iBublik commented on app/models/test.rb
> +  has_many :users, through: :test_attempts, dependent: :destroy
Зачем тебе удалять пользователей, который проходили тест, при удалении этого теста?

2018-09-18 19:13 UTC, iBublik commented on app/models/user.rb
> +  has_many :tests, through: :test_attempts, dependent: :destroy
Аналогично, зачем удалять тесты, которые проходил юзер, при его удалении?

2018-09-18 19:13 UTC, iBublik commented on db/migrate/20180916140850_add_user_to_tests.rb
> +    add_reference :tests, :user, foreign_key: true
Можно так - `add_reference :tests, :author, foreign_key: { to_table: :users }`. Меньше опций в модели придется указывать

2018-09-19 11:31 UTC, aivakhnenko commented on db/migrate/20180916140850_add_user_to_tests.rb
> +    add_reference :tests, :user, foreign_key: true
А какое отличие между `add_reference :tests, :author, foreign_key: { to_table: :users }` и `add_reference :tests, :author, foreign_key: true` ?
В обоих случаях для таблицы tests в schema.rb создаются строчки:
`    t.integer "author_id"`
`    t.index ["author_id"], name: "index_tests_on_author_id"`
И в обоих случаях в test.rb мне необходимо писать`belongs_to :author, class_name: "User"` .
Я думал в случае использования `{ to_table: :users }` мне не надо будет писать `class_name: "User"` .

2018-09-19 11:41 UTC, iBublik commented on db/migrate/20180916140850_add_user_to_tests.rb
> +    add_reference :tests, :user, foreign_key: true
По умолчанию имя таблицы вычисляется из 2го параметра, т.е. будет внешний ключ к таблице `authors`. Такой таблицы не существует, внешний ключ невалиден. Проблема в SQLite, он видимо внешние ключи вообще не создает. При использовании PostgreSQL миграция бы вообще упала

2018-09-19 14:49 UTC, aivakhnenko commented on db/migrate/20180916140850_add_user_to_tests.rb
> +    add_reference :tests, :user, foreign_key: true
А правильно ли, что в файле schema.rb не появляется никакой информации об связи поля tests.author_id с таблицей users? Получается об этом только файл миграции говорит. Или при разворачивании приложения на другой машине рельсы будут смотреть на файлы миграции, а не на файл schema.rb? Или даже просто при выполнении команды bin/rails db:reset

2018-09-19 14:57 UTC, merged