Lesson 8
aivakhnenko/test_guru pull request #8
Opened 2018-09-26 01:03 UTC by aivakhnenko

2018-09-26 16:09 UTC, iBublik requested changes

2018-09-26 16:09 UTC, iBublik commented on app/controllers/questions_controller.rb
>    def index
Этот экшн больше не нужен, вопросы выводятся на странице теста

2018-09-26 16:09 UTC, iBublik commented on app/helpers/questions_helper.rb
> +    "#{HEADER[action]} #{question.test.title} Question"
Опираться надо на состояние вопроса (сохранен или нет), а не на экшн

2018-09-26 16:09 UTC, iBublik commented on app/views/questions/_question.html.erb
> +  <td><%= link_to 'Edit', edit_test_question_path(question.test, question) %></td>
А зачем ты убрал shallow ресурс? Это утяжелило роутинг

2018-09-26 16:09 UTC, iBublik commented on app/views/questions/edit.html.erb
> +<%= render 'new_edit' %>
Зачем еще один паршл? Все содержимое `new_edit` можно в паршл формы поместить

2018-09-26 16:09 UTC, iBublik commented on app/views/questions/index.html.erb
> +<%= render 'shared/test_questions' %>
Этот шаблон больше не нужен

2018-09-26 16:09 UTC, iBublik commented on app/views/tests/show.html.erb
> +<%= render 'shared/test_questions' %>
Нужно какую-то инфу по тесту вывести. А рендерить список вопросов стоит через анонимный паршл (`render @questions`)

2018-09-26 18:27 UTC, aivakhnenko commented on app/views/questions/_question.html.erb
> +  <td><%= link_to 'Edit', edit_test_question_path(question.test, question) %></td>
Я вообще не совсем понимаю смысл вложенности ресурсов, если есть рекомендация не делать вложенность больше двух. Получается вопросы в тест мы вкладываем, а тест в категорию, ответы в вопрос и тесты в автора - нет. Как-то не системно получается. Плюс наличие shallow еще меньше прозрачности делает. Вроде пользователь создавал вопрос для теста (/tests/1/quesions/new). Потом он смотрит на список вопросов для этого теста (/tests/1/questions). Затем он проваливается в один из вопросов, и вот он уже вне какого-либо теста (/questions/11). Как, почему, зачем?.. Мне как-то ближе, когда используется единый подход.

2018-09-27 05:39 UTC, iBublik commented on app/controllers/questions_controller.rb
> +    render :edit
А зачем так делать-то? Сейчас может у тебя и совпадают шаблоны new и edit, но вряд ли так будет всегда

2018-09-27 05:39 UTC, iBublik commented on app/views/questions/_question.html.erb
> +  <td><%= link_to 'Edit', edit_test_question_path(question.test, question) %></td>
Мы не вкладываем тесты в категории, потому что у теста может отсутствовать категория. Мы не вкладываем тесты в "автора", потому что автором теста должен быть текущий пользователь (это мы реализуем с аутентификацией), иначе зная id пользователя ты бы мог сделать автором теста любого пользователя. Остальные вложения вполне можно сделать, тут никто не запрещает этого.
Вложенность делают, когда url не имеет смысла без родительского ресурса. Допустим, создание вопроса без теста выглядит глупо. А вот для просмотра созданного вопроса нам вообще неважно к какому тесту он относится. К тому же, это как раз позволяет избежать глубокого вложения - иначе, по твоей логике, для создания ответа пришлось бы использовать url `/tests/1/questions/1/answers`.
shallow еще можно выбросить в публичной части сайта, чтобы упросить навигацию пользователя. Но допустим у нас на сайте страница products#show не вложена в категорию. Видимо с точки зрения SEO короткие url лучше

2018-09-27 18:41 UTC, merged